[#BCNDEV218] - change Go generated code to add JSON support
kochavalabs/mazzaroth-xdr pull request #56
Opened 2021-03-26 15:11 UTC by lightyear15

## Description 
xdr-codegen has been changed to support json marshaling/unmarshaling
this change updates the generated file

## Related issue
https://app.asana.com/0/1200104933466235/1200104838618440/f

## Motivation & Context
Very first step of the ongoing milestone of implementing a mazzaroth proxy to provide access to mazzaroth network using JSON and stored keys rather than xdr

2021-03-29 12:47 UTC, jeff1010322 requested changes
Overall looks good!  The only issue is a warnings when the xdrmaxsize tag and json tag are on the same field. Example:
```
Timestamp string `xdrmaxsize:"256",json:"timestamp"`
``` 
It says these should be separated by spaces, not commas:
"struct field tag `xdrmaxsize:"256",json:"timestamp"` not compatible with reflect.StructTag.Get: key:"value" pairs not separated by spaces"

2021-03-29 13:01 UTC, lightyear15 commented
> Overall looks good! The only issue is a warnings when the xdrmaxsize tag and json tag are on the same field. Example:
> 
> ```
> Timestamp string `xdrmaxsize:"256",json:"timestamp"`
> ```
> 
> It says these should be separated by spaces, not commas:
> "struct field tag `xdrmaxsize:"256",json:"timestamp"` not compatible with reflect.StructTag.Get: key:"value" pairs not separated by spaces"

my bad :man_facepalming:

2021-03-29 16:07 UTC, jeff1010322 approved these changes
LGTM

2021-03-30 08:28 UTC, jmilet approved these changes

2021-03-30 13:36 UTC, merged